name: AWS OIDC Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  aws-oidc-test:
    name: Test GitHub OIDC to AWS
    runs-on: ubuntu-latest

    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::438064565553:role/GitHubActions-Terraform-Dev
          aws-region: ap-south-2
          role-session-name: GitHubActionsOIDCTest
          allowed-account-ids: 438064565553

      - name: Verify AWS identity
        run: |
          echo "===== AWS IDENTITY ====="
          aws sts get-caller-identity

          echo
          echo "===== AWS REGION ====="
          aws configure get region

      - name: Verify read-only access
        run: |
          echo "===== EC2 ====="
          aws ec2 describe-vpcs \
            --region ap-south-2 \
            --query 'Vpcs[0:3].[VpcId,CidrBlock]' \
            --output table

          echo
          echo "===== ROUTE 53 ====="
          aws route53 list-hosted-zones \
            --query 'HostedZones[0:5].[Id,Name]' \
            --output table

          echo
          echo "===== ACM ====="
          aws acm list-certificates \
            --region ap-south-2 \
            --query 'CertificateSummaryList[0:5].[DomainName,Status]' \
            --output table

      - name: Verify state bucket access
        run: |
          echo "===== TERRAFORM STATE BUCKET ====="

          aws s3api head-bucket \
            --bucket aws-production-platform-terraform-state

          echo "Terraform state bucket is accessible."
